### ISSUE TITLE
CSRF Validation issue with Magento 2.3.6-p1

### ISSUE THREAD

**Issue by kess78** [payrexx/magento-payrexx-gateway#1]
Hello guys,
trying to implement webhook but magento returns redirect 302 with the following in debug log:
` main.DEBUG: Request validation failed for action "Payrexx\PaymentGateway\Controller\Payment\Webhook\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at /var/www/www.mysite.com/vendor/magento/framework/App/Request/CsrfValidator.php:105)"} []`

Do you have some hints to resolve ?

**Comment by noahming** [comment]
Hi @kess78 

Our plugin has only been successfully tested with version 2.2.2 and 2.2.3 of Magento.
I'll check with the development team when compatibility for newer versions will be implemented.

Best regards Noah
