### ISSUE TITLE
WebHook: Transaction is not inserted after successful payment (Magento 2.3.6-p1)

### ISSUE THREAD

**Issue by kess78** [payrexx/magento-payrexx-gateway#2]
The Webhook call works, the call returns OK, everything OK in Dashboard, magento2 logs do not tell absolutely nothing.
The Order Status becomes "Processing" (so the webhook is executed) but no transaction is inserted.

If you need any further info, please let me know

**Comment by noahming** [comment]
Hi @kess78 

Could you share your exact Magento 2 Version?
Do you have a staging system where the issue can be reproduced?

Best regards Noah from Payrexx
