### ISSUE TITLE
Installing of the module via composer

### ISSUE THREAD

**Issue by a-litvin** [payrexx/magento-payrexx-gateway#20]
Hi,

I'm trying to install the module on Magento 2.4, php 8 via composer. I cannot install it, because php 8 doesn't satisfy the php requirements list in composer.json:  ~5.5.0|~5.6.0|^7.0. Could you update composer.json with php 8 as well?

**Comment by vekkon** [comment]
Hi @a-litvin 
Checkout the new version of this plugin 1.3.2 which includes PHP 8 in the composer.json
