### ISSUE TITLE
Payment method icons in checkout

### ISSUE THREAD

**Issue by a-litvin** [payrexx/magento-payrexx-gateway#24]
Hi,

On the https://docs.payrexx.com/merchant/integration/e-commerce/magento-2 it's claimed, that the module supports of showing of the payment method icons on checkout: https://i.imgur.com/RsTsdS7.png.

I don't see, how to enable it. And looking at the _vendor/payrexx/payment-gateway/view/frontend/web/template/payment/payment-method.html_ I'm not sure, that it's possible.

**Magento** 2.4.5.
**payrexx/payment-gateway** 1.3.5.

**Comment by vekkon** [comment]
Hi @a-litvin 
There is currently no option to show logos for the available payment methods in the Magento 2 checkout.
There is a task pending which solves this problem. The task is not yet planned in and therefore no due date is available yet.

Feel free to create/submit a pull request to solve this issue. We offer a library with all necessary logos: nm99@gmx.ch

**Comment by vekkon** [comment]
Hi @a-litvin 
Your issue just has been solved in the latest version of the plugin (1.3.7).

Best regards
