### ISSUE TITLE
Shopping cart empty when the transaction is cancelled.

### ISSUE THREAD

**Issue by madnazz** [payrexx/magento-payrexx-gateway#3]
There is a problem with the plugin, when the customer is redirected to the gateway and then cancels the payment, he is redirected back to the shop, then the message appears that the shopping cart is empty. The correct way would be if the customer is redirected to the shopping cart and the items are still available. Is there a solution coming soon?

We use Magento 2.4.2

Thanks!

**Comment by vekkon** [comment]
Hi madnazz

We added a small fix in the plugin with our last commit.
In the checkout there now appears a cancel button. If this is used, the cart will be recreated once the customer gets back to the shop. Let us know if this helps

**Comment by madnazz** [comment]
i tested it, but it doesn't solve the problem. the process is wrong the order is processed as soon as "pay" is clicked in the checkout, regardless of whether the transaction was successful or not.

**Comment by vekkon** [comment]
The cart should be rebuilt once the payment is cancelled.
How do you cancel the payment exactly? Are you using the cancel button in the Payrexx checkout form?
